   version: '3.8'

   services:
     cqrscommand:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "8080:8080"
         - "8081:8081"
       depends_on:
         - db
       environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - ConnectionStrings__DefaultConnection=Host=db;Database=mypostgreedatabase;Username=postgres;Password=admin

     db:
       image: postgres:latest
       environment:
         POSTGRES_DB: mypostgreedatabase
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: admin
       ports:
         - "5432:5432"
   